import AppKit
import SwiftUI
import UniformTypeIdentifiers

private enum Palette {
    static let background = Color(red: 0.045, green: 0.043, blue: 0.052)
    static let panel = Color(red: 0.092, green: 0.086, blue: 0.102)
    static let panelRaised = Color(red: 0.135, green: 0.114, blue: 0.127)
    static let border = Color(red: 0.27, green: 0.20, blue: 0.21)
    static let red = Color(red: 0.96, green: 0.25, blue: 0.23)
    static let gold = Color(red: 1.00, green: 0.74, blue: 0.36)
    static let muted = Color(red: 0.66, green: 0.61, blue: 0.63)
    static let white = Color(red: 0.98, green: 0.94, blue: 0.91)
}

private enum GamePhase: Equatable {
    case ready, warning, download, ransom, crucifix, thankYou, scare, defeat, escaped, paid, expired
}

struct Coin: Identifiable {
    let id = UUID()
    let value: Int
    let drawer: Int
    let crucifix: Bool
}

@MainActor
private final class Game: ObservableObject {
    static let shared = Game()
    @Published var phase: GamePhase = .ready
    @Published var ransomAmount = 500
    @Published var duration = 90
    @Published private(set) var due = 500
    @Published private(set) var secondsLeft = 90
    @Published private(set) var warningSeconds = 3
    @Published private(set) var warningProgress = 0.0
    @Published private(set) var downloadProgress = 0.0
    @Published private(set) var coins: [Coin] = []
    @Published var selectedDrawer = 0
    @Published private(set) var collected = 0
    @Published private(set) var selectedFolderName = "Папка игры (по умолчанию)"
    @Published private(set) var coinCount = 0
    @Published private(set) var defeatSeconds = 20

    private var warningStarted = Date.distantPast
    private var downloadStarted = Date.distantPast
    private var installSoundPlayed = false
    private var ransomDeadline = Date.distantPast
    private var defeatEndsAt = Date.distantPast
    private var outcomeEndsAt = Date.distantPast
    private var nextTauntAt = Date.distantPast
    private var ticker: Timer?
    private var eventMonitor: Any?
    private var selectedFolders: [URL] = []
    private let coinStore = CoinStore()
    private let soundtrack = Soundtrack()
    private let taunts = TauntManager()
    private let ransomPanel = RansomPanelManager()
    private let defeatOverlay = DefeatOverlayManager()
    private let outcomeOverlay = OutcomeOverlayManager()
    private weak var mainWindow: NSWindow?
    private var hasAutoStarted = false

    private init() {
#if QA
        duration = 8
#endif
        let timer = Timer(timeInterval: 0.2, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.tick() }
        }
        RunLoop.main.add(timer, forMode: .common)
        ticker = timer
    }

    func autoStartOnce() {
        guard !hasAutoStarted else { return }
        hasAutoStarted = true
        start()
    }

    func installActivityMonitor() {
        guard eventMonitor == nil else { return }
        NSApp.windows.forEach { $0.acceptsMouseMovedEvents = true }
        eventMonitor = NSEvent.addLocalMonitorForEvents(matching: [.mouseMoved, .leftMouseDragged, .rightMouseDragged, .keyDown]) { [weak self] event in
            // The game only observes input inside its own foreground window.
            if event.type == .keyDown, event.modifierFlags.contains(.command),
               event.charactersIgnoringModifiers?.lowercased() == "q" {
                NSApp.terminate(nil)
                return nil
            }
            self?.noticeActivity()
            return event
        }
    }

    func removeActivityMonitor() {
        if let eventMonitor { NSEvent.removeMonitor(eventMonitor) }
        eventMonitor = nil
    }

    func start() {
        guard phase == .ready || phase == .escaped || phase == .expired else { return }
        coinStore.cleanup()
        soundtrack.stop()
        taunts.closeAll()
        defeatOverlay.close()
        outcomeOverlay.close()
        due = ransomAmount
        secondsLeft = duration
        collected = 0
        coins = []
        coinCount = 0
        warningSeconds = 3
        warningProgress = 0
        downloadProgress = 0
        warningStarted = Date()
        phase = .warning
        Sound.play("spawn")
        updateWindowCloseButton()
    }

    func noticeActivity() {
        // Ignore the initial mouse event generated by clicking Start.
        guard phase == .warning, Date().timeIntervalSince(warningStarted) > 0.45 else { return }
        beginDownload()
    }

    func tick() {
        switch phase {
        case .warning:
            warningProgress = Date().timeIntervalSince(warningStarted) / 3
            warningSeconds = max(0, 3 - Int(Date().timeIntervalSince(warningStarted)))
#if QA
            if warningProgress >= 0.25 {
                beginDownload()
                return
            }
#endif
            if warningProgress >= 1 {
                beginDownload()
            }
        case .download:
            downloadProgress = min(1, Date().timeIntervalSince(downloadStarted) / 2.2)
            if downloadProgress >= 0.36 && !installSoundPlayed {
                installSoundPlayed = true
                Sound.play("install")
            }
            if downloadProgress >= 1 { beginRansom() }
        case .ransom:
            let now = Date()
            secondsLeft = max(0, Int(ceil(ransomDeadline.timeIntervalSince(now))))
            soundtrack.update(elapsed: duration - secondsLeft, duration: duration)
            if now >= nextTauntAt && secondsLeft > 0 {
                taunts.spawn(count: secondsLeft <= 20 ? 2 : 1)
                Sound.play("tauntSpawn")
                nextTauntAt = now.addingTimeInterval(
                    secondsLeft <= 20 ? Double.random(in: 1.5...3.0) : Double.random(in: 3.0...5.0)
                )
            }
            if secondsLeft == 0 {
                beginDefeat()
            }
        case .crucifix:
            if Date() >= outcomeEndsAt { beginThankYou() }
        case .thankYou:
            if Date() >= outcomeEndsAt { NSApp.terminate(nil) }
        case .scare:
            if Date() >= outcomeEndsAt { beginBlackout() }
        case .defeat:
            defeatSeconds = max(0, Int(ceil(defeatEndsAt.timeIntervalSinceNow)))
            if defeatSeconds == 0 {
                NSApp.terminate(nil)
            }
        default:
            break
        }
    }

    func pay(_ id: UUID) {
        guard phase == .ransom, let index = coins.firstIndex(where: { $0.id == id }) else { return }
        guard coinStore.consume(id) else { return }
        let coin = coins.remove(at: index)
        coinCount = coins.count
        if coin.crucifix {
            due = 0
            Sound.play("crucifix")
        } else {
            due = max(0, due - coin.value)
            collected += coin.value
            Sound.play("cash")
        }
        if due == 0 {
            beginVictory(crucifix: coin.crucifix)
        }
    }

    func payFile(at url: URL) {
        guard let id = coinStore.coinID(at: url) else { return }
        pay(id)
    }

    func openCoinsInFinder() { coinStore.openInFinder(all: true) }

    func chooseCoinsToPay() {
        guard phase == .ransom else { return }
        let panel = NSOpenPanel()
        panel.message = "Выбери файлы .gold или .crucifix, созданные этим раундом."
        panel.prompt = "Отдать монеты"
        panel.canChooseFiles = true
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = true
        panel.directoryURL = coinStore.currentRoot
        if panel.runModal() == .OK {
            for url in panel.urls { payFile(at: url) }
        }
    }

    func chooseFolder() {
        guard phase == .ready || phase == .escaped || phase == .expired else { return }
        let panel = NSOpenPanel()
        panel.message = "Выбери до восьми мест (например, Документы, Загрузки, Рабочий стол). В каждом появятся только разноцветные папки игры. Системную /Applications и виртуальные «Недавние» приложение не изменяет."
        panel.prompt = "Выбрать папки"
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.allowsMultipleSelection = true
        if panel.runModal() == .OK, !panel.urls.isEmpty {
            let allowed = Array(panel.urls.filter { CoinStore.isAllowedRoot($0) }.prefix(8))
            if allowed.isEmpty {
                let alert = NSAlert()
                alert.messageText = "Выбери папки внутри домашней папки Mac"
                alert.informativeText = "Системные каталоги, включая /Applications, не используются. Папка «Программы» внутри твоей домашней папки подходит."
                alert.runModal()
            } else {
                selectedFolders = allowed
                selectedFolderName = allowed.map(\.lastPathComponent).joined(separator: " · ")
            }
        }
    }

    func useGameFolder() {
        selectedFolders = []
        selectedFolderName = "Папка игры (по умолчанию)"
    }

    func useStandardFolders() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let names = ["Desktop", "Documents", "Downloads", "Pictures", "Music", "Movies", "Applications"]
        selectedFolders = names.map { home.appendingPathComponent($0, isDirectory: true) }
            .filter { CoinStore.isAllowedRoot($0) && FileManager.default.fileExists(atPath: $0.path) }
        selectedFolderName = selectedFolders.isEmpty
            ? "Папка игры (по умолчанию)"
            : "\(selectedFolders.count) мест: " + selectedFolders.map(\.lastPathComponent).joined(separator: " · ")
    }

    func shutdown() {
        coinStore.cleanup()
        soundtrack.stop()
        taunts.closeAll()
        ransomPanel.close()
        defeatOverlay.close()
        outcomeOverlay.close()
        removeActivityMonitor()
        ticker?.invalidate()
    }

    private func beginDownload() {
        guard phase == .warning else { return }
        phase = .download
        downloadStarted = Date()
        installSoundPlayed = false
        downloadProgress = 0
        Sound.play("attack")
    }

    private func beginRansom() {
        guard phase == .download else { return }
        phase = .ransom
        secondsLeft = duration
        var generated: [Coin] = [Coin(value: 10, drawer: 0, crucifix: false)]
        var sum = 10
        let values = [10, 10, 10, 10, 50, 50, 50, 100, 100, 150, 200]
        while sum < Int(Double(ransomAmount) * 1.3) || generated.count < max(12, selectedFolders.count * 2) {
            let value = values.randomElement() ?? 50
            generated.append(Coin(value: value, drawer: generated.count % 6, crucifix: false))
            sum += value
        }
        generated.append(Coin(value: 0, drawer: Int.random(in: 0..<6), crucifix: true))
        if Int.random(in: 0..<3) == 0 {
            generated.append(Coin(value: 500, drawer: Int.random(in: 0..<6), crucifix: false))
        }
        let tutorial = generated.removeFirst()
        let distribution = [tutorial] + generated.shuffled()
        var placed = coinStore.scatter(distribution, in: selectedFolders)
        if placed.isEmpty && !selectedFolders.isEmpty {
            placed = coinStore.scatter(distribution, in: [])
        }
        coins = placed
        coinCount = placed.count
        due = min(ransomAmount, placed.filter { !$0.crucifix }.reduce(0) { $0 + $1.value })
        if due == 0 {
            phase = .expired
            return
        }
        ransomDeadline = Date().addingTimeInterval(TimeInterval(duration))
        nextTauntAt = Date().addingTimeInterval(3)
        selectedDrawer = Int.random(in: 0..<6)
        soundtrack.update(elapsed: 0, duration: duration)
        mainWindow = NSApp.windows.first(where: { $0.title == "doors" })
        mainWindow?.orderOut(nil)
        // The floating game panel stays visible, without a Dock icon to close.
        // Cmd+Q still terminates the foreground game through the event monitor.
        NSApp.setActivationPolicy(.accessory)
        ransomPanel.show(game: self)
        taunts.spawn(count: 5)
        Sound.play("tauntSpawn")
        coinStore.openInFinder(all: false)
#if QA
        let qaOutcome = ProcessInfo.processInfo.environment["RANS0M_QA_OUTCOME"]
        if qaOutcome == "thanks" || qaOutcome == "crucifix" {
            DispatchQueue.main.asyncAfter(deadline: .now() + 1) { [weak self] in
                guard let self, self.phase == .ransom else { return }
                if qaOutcome == "crucifix", let item = self.coins.first(where: \.crucifix) {
                    self.pay(item.id)
                } else if qaOutcome == "thanks" {
                    for item in self.coins where !item.crucifix {
                        guard self.phase == .ransom else { break }
                        self.pay(item.id)
                    }
                }
            }
        }
#endif
    }

    private func beginDefeat() {
        guard phase == .ransom else { return }
        phase = .scare
        outcomeEndsAt = Date().addingTimeInterval(3)
        coins = []
        coinCount = 0
        coinStore.cleanup()
        soundtrack.stop()
        taunts.closeAll()
        ransomPanel.close()
        Sound.play("attack")
        outcomeOverlay.show(.scare)
    }

    private func beginBlackout() {
        guard phase == .scare else { return }
        outcomeOverlay.close()
        phase = .defeat
        defeatSeconds = 20
        defeatEndsAt = Date().addingTimeInterval(20)
        defeatOverlay.show(game: self)
    }

    private func beginVictory(crucifix: Bool) {
        phase = crucifix ? .crucifix : .thankYou
        coins = []
        coinCount = 0
        coinStore.cleanup()
        soundtrack.stop()
        taunts.closeAll()
        ransomPanel.close()
        if crucifix {
            outcomeOverlay.show(.crucifix)
            outcomeEndsAt = Date().addingTimeInterval(3)
        } else {
            beginThankYou()
        }
    }

    private func beginThankYou() {
        guard phase == .crucifix || phase == .thankYou else { return }
        phase = .thankYou
        outcomeOverlay.show(.thankYou)
        outcomeEndsAt = Date().addingTimeInterval(4)
        Sound.play("thankyou")
    }

    private func updateWindowCloseButton() {
        let locked = phase == .warning || phase == .download || phase == .ransom || phase == .crucifix || phase == .thankYou || phase == .scare || phase == .defeat
        for window in NSApp.windows where window.title == "doors" {
            window.standardWindowButton(.closeButton)?.isEnabled = !locked
            window.standardWindowButton(.miniaturizeButton)?.isEnabled = !locked
        }
    }
}

private enum Sound {
    private static var active: [NSSound] = []

    static func play(_ name: String) {
        guard let path = Bundle.main.path(forResource: name, ofType: "wav"),
              let sound = NSSound(contentsOfFile: path, byReference: false) else { return }
        sound.volume = 0.22
        sound.play()
        active.removeAll(where: { !$0.isPlaying })
        active.append(sound)
    }
}

private struct BundledImage: View {
    let name: String

    var body: some View {
        Group {
            if let path = Bundle.main.path(forResource: name, ofType: "png"),
               let image = NSImage(contentsOfFile: path) {
                Image(nsImage: image).resizable().interpolation(.high).scaledToFit()
            } else {
                Image(systemName: "eye.fill").resizable().scaledToFit().foregroundStyle(Palette.red)
            }
        }
    }
}

private struct GameView: View {
    @StateObject private var game = Game.shared
    @State private var isDropTarget = false

    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()
            if game.phase == .warning || game.phase == .download {
                cinematicOverlay
            }
        }
        .frame(minWidth: 950, minHeight: 680)
        .foregroundStyle(Palette.white)
        .preferredColorScheme(.dark)
        .onAppear {
            game.installActivityMonitor()
            game.autoStartOnce()
        }
    }

    private var header: some View {
        HStack(alignment: .center) {
            HStack(spacing: 12) {
                Image(systemName: "circle.hexagongrid.fill")
                    .font(.system(size: 27, weight: .black))
                    .foregroundStyle(Palette.red)
                VStack(alignment: .leading, spacing: 2) {
                    Text("doors").font(.system(size: 24, weight: .black, design: .monospaced)).tracking(3)
                    Text("MAC EDITION  /  RANS0M · A-90")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .tracking(1.5).foregroundStyle(Palette.muted)
                }
            }
            Spacer()
            HStack(spacing: 8) {
                Circle().fill(statusColor).frame(width: 7, height: 7)
                Text(statusText)
                    .font(.system(size: 11, weight: .bold, design: .monospaced))
                    .tracking(1)
            }
            .padding(.horizontal, 14).padding(.vertical, 9)
            .background(Palette.panelRaised, in: Capsule())
        }
        .padding(.horizontal, 27).padding(.vertical, 18)
    }

    private var statusColor: Color {
        switch game.phase {
        case .warning, .download, .ransom, .scare, .crucifix, .defeat: Palette.red
        case .thankYou: Palette.gold
        case .paid, .escaped: Palette.gold
        default: Palette.muted
        }
    }

    private var statusText: String {
        switch game.phase {
        case .ready: "ОЖИДАНИЕ"
        case .warning: "ЗАМРИ"
        case .download: "ЗАРАЖЕНИЕ"
        case .ransom: "АТАКА"
        case .crucifix: "РАСПЯТИЕ"
        case .thankYou: "СПАСЕНИЕ"
        case .scare: "ПОРАЖЕНИЕ"
        case .defeat: "ПОРАЖЕНИЕ"
        case .escaped: "ВЫ СПАСЛИСЬ"
        case .paid: "ОПЛАЧЕНО"
        case .expired: "ВРЕМЯ ВЫШЛО"
        }
    }

    private var mainPanel: some View {
        VStack(alignment: .leading, spacing: 20) {
            ZStack {
                RoundedRectangle(cornerRadius: 18).fill(Palette.panel)
                RoundedRectangle(cornerRadius: 18).stroke(Palette.border, lineWidth: 1)
                RadialGradient(colors: [Palette.red.opacity(game.phase == .warning || game.phase == .download || game.phase == .ransom ? 0.29 : 0.1), .clear], center: .center, startRadius: 20, endRadius: 280)
                    .clipShape(RoundedRectangle(cornerRadius: 18))
                VStack(spacing: 6) {
                    Text("///  ВИЗУАЛЬНЫЙ КОНТАКТ  ///")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .tracking(2).foregroundStyle(Palette.red.opacity(0.85))
                    BundledImage(name: game.phase == .download || game.phase == .ransom || game.phase == .expired ? "ransom_attack" : "ransom_idle")
                        .frame(width: 205, height: 205)
                        .shadow(color: Palette.red.opacity(0.34), radius: 30)
                    Text(portraitCaption)
                        .font(.system(size: 11, weight: .medium, design: .monospaced))
                        .tracking(1.2).foregroundStyle(Palette.muted)
                }
            }
            .frame(maxWidth: .infinity)
            .frame(height: 290)

            VStack(alignment: .leading, spacing: 12) {
                Text(headline)
                    .font(.system(size: 25, weight: .heavy, design: .monospaced))
                    .tracking(-0.7)
                    .foregroundStyle(game.phase == .ransom || game.phase == .warning || game.phase == .download ? Palette.red : Palette.white)
                    .lineLimit(2).minimumScaleFactor(0.8)
                Text(explanation)
                    .font(.system(size: 13)).foregroundStyle(Palette.muted)
                    .fixedSize(horizontal: false, vertical: true)
                    .lineSpacing(3)
            }
            .frame(maxWidth: .infinity, alignment: .leading)

            Spacer(minLength: 0)
            if game.phase == .ransom { progressPanel }
            actionButtons
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }

    private var portraitCaption: String {
        switch game.phase {
        case .warning: "НЕ ДВИГАЙСЯ  ·  \(game.warningSeconds)"
        case .download: "ЗАГРУЗКА..."
        case .ransom: "ЦЕЛЬ ОБНАРУЖЕНА"
        case .crucifix, .thankYou, .scare: "СИГНАЛ ПОТЕРЯН"
        case .defeat: "СИГНАЛ ПОТЕРЯН"
        case .paid, .escaped: "СИГНАЛ ПОТЕРЯН"
        default: "СИГНАЛ ОЖИДАЕТСЯ"
        }
    }

    private var headline: String {
        switch game.phase {
        case .ready: "ОН СЛЕДИТ ЗА ТОБОЙ."
        case .warning: "СТОЙ. НЕ ДВИГАЙСЯ."
        case .download: "ОН НАШЁЛ ТЕБЯ."
        case .ransom: "СОБЕРИ ЗОЛОТО."
        case .crucifix: "ОН УХОДИТ."
        case .thankYou: "СПАСИБО."
        case .scare: "ПОРАЖЕНИЕ."
        case .defeat: "ПОРАЖЕНИЕ."
        case .escaped: "ТЕБЯ НЕ ЗАМЕТИЛИ."
        case .paid: "ДОЛГ ПОГАШЕН."
        case .expired: "ВРЕМЯ ВЫШЛО."
        }
    }

    private var explanation: String {
        switch game.phase {
        case .ready: "При запуске RANS0M появляется сам. Во время предупреждения не двигай мышью и не нажимай клавиши три секунды."
        case .warning: "Если пошевелишь мышью или нажмёшь клавишу, RANS0M потребует выкуп. Замри, чтобы избежать атаки."
        case .download: "Монеты появляются как файлы. Найди их в Finder и перетащи сюда, пока не закончился таймер."
        case .ransom: "Найди файлы .gold в Finder и перетащи их в зону оплаты. .crucifix снимает весь долг."
        case .crucifix: "Распятие остановило монстра."
        case .thankYou: "Монеты собраны. Игра сейчас завершится."
        case .scare: "Монстр поймал тебя."
        case .defeat: "Чёрный экран продлится 20 секунд, затем приложение завершится."
        case .escaped: "Ты выдержал предупреждение. Система не пострадала. Можешь сыграть ещё раз."
        case .paid: "Монет хватило, чтобы снять выкуп."
        case .expired: "Раунд окончен. Созданные игрой монеты убраны; твои файлы остались нетронутыми."
        }
    }

    private var progressPanel: some View {
        VStack(alignment: .leading, spacing: 11) {
            HStack(alignment: .firstTextBaseline) {
                Text("ОСТАЛОСЬ").font(.system(size: 10, weight: .bold, design: .monospaced)).foregroundStyle(Palette.muted)
                Spacer()
                Text("\(game.due) G").font(.system(size: 23, weight: .heavy, design: .monospaced)).foregroundStyle(Palette.gold)
            }
            GeometryReader { proxy in
                ZStack(alignment: .leading) {
                    Capsule().fill(Palette.border)
                    Capsule().fill(Palette.gold)
                        .frame(width: proxy.size.width * CGFloat(game.ransomAmount - game.due) / CGFloat(max(1, game.ransomAmount)))
                }
            }
            .frame(height: 6)
            HStack {
                Text("СОБРАНО  \(game.collected) G")
                Spacer()
                Text(String(format: "%02d:%02d", game.secondsLeft / 60, game.secondsLeft % 60))
                    .foregroundStyle(game.secondsLeft <= 15 ? Palette.red : Palette.white)
            }
            .font(.system(size: 12, weight: .bold, design: .monospaced)).foregroundStyle(Palette.muted)
        }
        .padding(18)
        .background(Palette.panel, in: RoundedRectangle(cornerRadius: 14))
        .overlay(RoundedRectangle(cornerRadius: 14).stroke(Palette.border, lineWidth: 1))
    }

    private var actionButtons: some View {
        HStack(spacing: 10) {
            if game.phase == .ready || game.phase == .escaped || game.phase == .paid || game.phase == .expired {
                Button(action: game.start) {
                    Label(game.phase == .ready ? "НАЧАТЬ ИГРУ" : "ЕЩЁ РАУНД", systemImage: "play.fill")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(PrimaryButtonStyle())
            } else {
                Text("РАУНД ИДЁТ · ИЩИ МОНЕТЫ В FINDER")
                    .font(.system(size: 11, weight: .heavy, design: .monospaced))
                    .foregroundStyle(Palette.gold)
            }
        }
    }

    private var drawerPanel: some View {
        VStack(alignment: .leading, spacing: 17) {
            HStack {
                VStack(alignment: .leading, spacing: 4) {
                    Text(game.phase == .ransom ? "ПОИСК ЗОЛОТА" : "ПАРАМЕТРЫ ИГРЫ")
                        .font(.system(size: 17, weight: .heavy, design: .monospaced)).tracking(1)
                    Text(game.phase == .ransom ? "Открывай ящики · ищи монеты" : "Настрой следующий раунд")
                        .font(.system(size: 11)).foregroundStyle(Palette.muted)
                }
                Spacer()
                Image(systemName: game.phase == .ransom ? "shippingbox.fill" : "slider.horizontal.3")
                    .foregroundStyle(Palette.gold).font(.system(size: 21))
            }
            Rectangle().fill(Palette.border).frame(height: 1)

            if game.phase == .ransom {
                drawerGame.frame(maxHeight: .infinity)
            } else {
                ScrollView { settings }
                    .frame(maxHeight: .infinity)
            }
            Text("ТОЛЬКО СВОИ МОНЕТЫ  ·  БЕЗ ВЫКЛЮЧЕНИЯ MAC")
                .font(.system(size: 9, weight: .bold, design: .monospaced))
                .tracking(0.6).foregroundStyle(Palette.muted)
        }
        .padding(21)
        .frame(width: 400)
        .frame(maxHeight: .infinity, alignment: .topLeading)
        .background(Palette.panel, in: RoundedRectangle(cornerRadius: 18))
        .overlay(RoundedRectangle(cornerRadius: 18).stroke(Palette.border, lineWidth: 1))
    }

    private var settings: some View {
        VStack(alignment: .leading, spacing: 23) {
            settingRow(title: "РАЗМЕР ВЫКУПА", value: "\(game.ransomAmount) G", minus: {
                game.ransomAmount = max(100, game.ransomAmount - 100)
            }, plus: {
                game.ransomAmount = min(2000, game.ransomAmount + 100)
            })
            settingRow(title: "ВРЕМЯ НА СБОР", value: "\(game.duration) СЕК", minus: {
                game.duration = max(30, game.duration - 15)
            }, plus: {
                game.duration = min(180, game.duration + 15)
            })
            VStack(alignment: .leading, spacing: 8) {
                Text("КУДА ПОМЕЩАТЬ МОНЕТЫ")
                    .font(.system(size: 10, weight: .bold, design: .monospaced)).foregroundStyle(Palette.muted)
                Text(game.selectedFolderName)
                    .font(.system(size: 12, weight: .semibold)).lineLimit(1)
                HStack(spacing: 8) {
                    Button("ВЫБРАТЬ МЕСТА", action: game.chooseFolder)
                        .buttonStyle(SecondaryButtonStyle())
                    Button("СБРОС", action: game.useGameFolder)
                        .buttonStyle(SecondaryButtonStyle())
                }
                Button("СТАНДАРТНЫЕ ПАПКИ MAC", action: game.useStandardFolders)
                    .buttonStyle(SecondaryButtonStyle())
                Text("В каждом месте появятся разноцветные папки игры, часть из них — пустышки. «Недавние» — виртуальный список Finder, а системная /Applications не меняется.")
                    .font(.system(size: 10)).foregroundStyle(Palette.muted)
            }
            VStack(alignment: .leading, spacing: 10) {
                Text("КАК ЭТО РАБОТАЕТ")
                    .font(.system(size: 10, weight: .heavy, design: .monospaced)).foregroundStyle(Palette.gold)
                instruction("01", "RANS0M появляется при запуске.")
                instruction("02", "Замри на 3 секунды, чтобы спастись.")
                instruction("03", "Иначе ищи монеты в Finder.")
            }
            .padding(17)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Palette.panelRaised, in: RoundedRectangle(cornerRadius: 12))
            Text("Адаптация для macOS. Исходный проект: Ixar. Doors и RANSOM/A-90: LSPLASH. Неофициальный некоммерческий фан-проект.")
                .font(.system(size: 10)).foregroundStyle(Palette.muted)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(.top, 8).padding(.bottom, 10)
    }

    private func settingRow(title: String, value: String, minus: @escaping () -> Void, plus: @escaping () -> Void) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Text(title).font(.system(size: 10, weight: .bold, design: .monospaced)).foregroundStyle(Palette.muted)
            HStack {
                Text(value).font(.system(size: 20, weight: .heavy, design: .monospaced)).foregroundStyle(Palette.gold)
                Spacer()
                Button(action: minus) { Image(systemName: "minus") }.buttonStyle(StepButtonStyle())
                Button(action: plus) { Image(systemName: "plus") }.buttonStyle(StepButtonStyle())
            }
        }
    }

    private func instruction(_ number: String, _ copy: String) -> some View {
        HStack(alignment: .firstTextBaseline, spacing: 10) {
            Text(number).font(.system(size: 10, weight: .heavy, design: .monospaced)).foregroundStyle(Palette.gold)
            Text(copy).font(.system(size: 11)).foregroundStyle(Palette.white)
        }
    }

    private var drawerGame: some View {
        VStack(alignment: .leading, spacing: 17) {
            HStack(spacing: 12) {
                Image(systemName: "folder.fill").font(.system(size: 26)).foregroundStyle(Palette.gold)
                VStack(alignment: .leading, spacing: 3) {
                    Text("\(game.coinCount) ФАЙЛОВ-МОНЕТ")
                        .font(.system(size: 13, weight: .heavy, design: .monospaced))
                    Text(".gold1–.gold6  /  .crucifix")
                        .font(.system(size: 10, design: .monospaced)).foregroundStyle(Palette.muted)
                }
            }
            .padding(15).frame(maxWidth: .infinity, alignment: .leading)
            .background(Palette.panelRaised, in: RoundedRectangle(cornerRadius: 11))
            Button {
                game.openCoinsInFinder()
            } label: {
                Label("ОТКРЫТЬ ПАПКУ В FINDER", systemImage: "folder.badge.plus")
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(PrimaryButtonStyle())
            Text("В самой первой папке лежит одна монета на 10 G. Другие разноцветные папки могут быть пустыми. Перетаскивай найденное сюда.")
                .font(.system(size: 12)).foregroundStyle(Palette.muted)
                .fixedSize(horizontal: false, vertical: true)
            Spacer(minLength: 0)
            ZStack {
                RoundedRectangle(cornerRadius: 11)
                    .fill(isDropTarget ? Palette.gold.opacity(0.18) : Palette.background)
                RoundedRectangle(cornerRadius: 11)
                    .strokeBorder(isDropTarget ? Palette.gold : Palette.border, style: StrokeStyle(lineWidth: 1.5, dash: [6, 5]))
                VStack(spacing: 5) {
                    Image(systemName: "arrow.down.to.line.compact").font(.system(size: 19)).foregroundStyle(Palette.gold)
                    Text("ПЕРЕТАЩИ ФАЙЛ-МОНЕТУ СЮДА")
                        .font(.system(size: 10, weight: .heavy, design: .monospaced)).tracking(0.5)
                }
            }
            .frame(height: 116)
            .onDrop(of: [.fileURL], isTargeted: $isDropTarget) { providers in
                for provider in providers {
                    provider.loadItem(forTypeIdentifier: UTType.fileURL.identifier, options: nil) { item, _ in
                        let fileURL: URL?
                        if let url = item as? URL { fileURL = url }
                        else if let data = item as? Data { fileURL = URL(dataRepresentation: data, relativeTo: nil) }
                        else if let text = item as? String { fileURL = URL(string: text) }
                        else { fileURL = nil }
                        if let fileURL { DispatchQueue.main.async { game.payFile(at: fileURL) } }
                    }
                }
                return true
            }
            Button("ВЫБРАТЬ ФАЙЛ-МОНЕТУ…") { game.chooseCoinsToPay() }
                .buttonStyle(SecondaryButtonStyle())
        }
    }

    private var cinematicOverlay: some View {
        ZStack {
            Color(red: 0.12, green: 0.0, blue: 0.0).ignoresSafeArea()
            RadialGradient(colors: [Palette.red.opacity(0.65), .clear], center: .center, startRadius: 30, endRadius: 560)
                .ignoresSafeArea()
            VStack(spacing: 16) {
                HStack {
                    Text("RANS0M  //  \(game.phase == .warning ? "СТОЙ" : "ОБНАРУЖЕН")")
                    Spacer()
                }
                .font(.system(size: 12, weight: .heavy, design: .monospaced))
                .padding(.horizontal, 30).padding(.top, 15)
                Spacer()
                if game.phase == .warning {
                    if game.warningProgress > 0.18 {
                        BundledImage(name: "stop_sign").frame(width: 105, height: 105)
                    }
                    BundledImage(name: "ransom_idle")
                        .frame(width: game.warningProgress > 0.18 ? 300 : 220,
                               height: game.warningProgress > 0.18 ? 300 : 220)
                        .offset(x: game.warningProgress > 0.18 ? 0 : 165,
                                y: game.warningProgress > 0.18 ? 0 : -75)
                    Text("НЕ ДВИГАЙСЯ").font(.system(size: 42, weight: .black, design: .monospaced)).tracking(5)
                    Text("\(game.warningSeconds)").font(.system(size: 27, weight: .bold, design: .monospaced))
                } else {
                    BundledImage(name: "ransom_attack")
                        .frame(width: 330, height: 330)
                        .offset(x: CGFloat.random(in: -11...11), y: CGFloat.random(in: -11...11))
                    Text("DOWNLOADING...").font(.system(size: 38, weight: .black, design: .monospaced)).tracking(3)
                    ProgressView(value: game.downloadProgress)
                        .tint(Palette.red).frame(width: 440)
                }
                Spacer()
                Text("ИГРОВАЯ ИМИТАЦИЯ · CMD+Q ДЛЯ ВЫХОДА")
                    .font(.system(size: 10, weight: .bold, design: .monospaced))
                    .foregroundStyle(Palette.white.opacity(0.6)).padding(.bottom, 22)
            }
        }
    }

    private var footer: some View {
        HStack {
            Text("RANS0M  /  ИГРОВАЯ ИМИТАЦИЯ")
            Spacer()
            Text("CMD+Q — ВЫХОД ИЗ ПРИЛОЖЕНИЯ")
        }
        .font(.system(size: 9, weight: .bold, design: .monospaced))
        .tracking(1).foregroundStyle(Palette.muted)
        .padding(.horizontal, 27).padding(.bottom, 18)
    }
}

private final class RansomPanelManager {
    private var panel: NSPanel?

    @MainActor
    func show(game: Game) {
        close()
        let width: CGFloat = 560
        let height: CGFloat = 430
        let visible = NSScreen.main?.visibleFrame ?? NSRect(x: 0, y: 0, width: 1200, height: 800)
        let maxX = max(visible.minX, visible.maxX - width)
        let maxY = max(visible.minY, visible.maxY - height)
        let x = CGFloat.random(in: visible.minX...maxX)
        let y = CGFloat.random(in: visible.minY...maxY)
        let window = NSPanel(contentRect: NSRect(x: x, y: y, width: width, height: height),
                             styleMask: [.titled], backing: .buffered, defer: false)
        window.title = "doors — выкуп"
        window.isReleasedWhenClosed = false
        window.level = .floating
        window.hidesOnDeactivate = false
        window.isMovableByWindowBackground = true
        window.backgroundColor = NSColor(red: 0.48, green: 0.07, blue: 0.06, alpha: 1)
        window.standardWindowButton(.closeButton)?.isEnabled = false
        window.contentView = NSHostingView(rootView: RansomPanelView(game: game))
        window.makeKeyAndOrderFront(nil)
        panel = window
    }

    func close() {
        panel?.close()
        panel = nil
    }
}

private final class KeyableBlackPanel: NSPanel {
    override var canBecomeKey: Bool { true }
}

private enum OutcomeKind { case scare, crucifix, thankYou }

@MainActor
private final class OutcomeOverlayManager {
    private var windows: [NSPanel] = []

    func show(_ kind: OutcomeKind) {
        close()
        for screen in NSScreen.screens {
            let window = KeyableBlackPanel(contentRect: screen.frame, styleMask: [.borderless],
                                           backing: .buffered, defer: false)
            window.isReleasedWhenClosed = false
            window.level = .screenSaver
            window.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
            window.contentView = NSHostingView(rootView: OutcomeView(kind: kind, isPrimary: screen == NSScreen.main))
            window.orderFrontRegardless()
            if screen == NSScreen.main { window.makeKey() }
            windows.append(window)
        }
        NSApp.activate(ignoringOtherApps: true)
    }

    func close() {
        windows.forEach { $0.close() }
        windows.removeAll()
    }
}

private struct OutcomeView: View {
    let kind: OutcomeKind
    let isPrimary: Bool
    @State private var vanishing = false

    var body: some View {
        ZStack {
            if kind == .thankYou {
                LinearGradient(colors: [Color(red: 0.01, green: 0.11, blue: 0.03),
                                        Color(red: 0.03, green: 0.49, blue: 0.12)],
                               startPoint: .top, endPoint: .bottom).ignoresSafeArea()
            } else {
                Color(red: kind == .scare ? 0.47 : 0.17, green: 0, blue: 0).ignoresSafeArea()
            }
            if isPrimary {
                VStack(spacing: 12) {
                    BundledImage(name: kind == .thankYou ? "ok_sign" :
                                 (kind == .scare ? "ransom_attack" : "ransom_crucifix"))
                        .frame(maxWidth: kind == .scare ? .infinity : 440,
                               maxHeight: kind == .scare ? .infinity : 520)
                        .scaleEffect(kind == .crucifix && vanishing ? 0.15 : 1)
                        .opacity(kind == .crucifix && vanishing ? 0 : 1)
                        .shadow(color: kind == .thankYou ? .green : .red, radius: 50)
                    if kind == .thankYou {
                        BundledImage(name: "thx_txt").frame(maxWidth: 600, maxHeight: 150)
                    } else if kind == .crucifix {
                        Text("REPENT")
                            .font(.system(size: 58, weight: .black, design: .monospaced))
                            .foregroundStyle(.white)
                    }
                }
                .padding(kind == .scare ? 18 : 0)
            }
        }
        .onAppear {
            if kind == .crucifix {
                withAnimation(.easeIn(duration: 2.6)) { vanishing = true }
            }
        }
    }
}

@MainActor
private final class DefeatOverlayManager {
    private var windows: [NSPanel] = []

    func show(game: Game) {
        close()
        for screen in NSScreen.screens {
            let window = KeyableBlackPanel(contentRect: screen.frame, styleMask: [.borderless],
                                           backing: .buffered, defer: false)
            window.isReleasedWhenClosed = false
            window.backgroundColor = .black
            window.level = .screenSaver
            window.collectionBehavior = [.canJoinAllSpaces, .fullScreenAuxiliary]
            window.contentView = NSHostingView(rootView: DefeatView(game: game, isPrimary: screen == NSScreen.main))
            window.orderFrontRegardless()
            if screen == NSScreen.main { window.makeKey() }
            windows.append(window)
        }
        NSApp.activate(ignoringOtherApps: true)
    }

    func close() {
        windows.forEach { $0.close() }
        windows.removeAll()
    }
}

private struct DefeatView: View {
    @ObservedObject var game: Game
    let isPrimary: Bool

    var body: some View {
        Color.black.ignoresSafeArea()
    }
}

private struct RansomPanelView: View {
    @ObservedObject var game: Game
    @State private var isDropTarget = false

    var body: some View {
        ZStack {
            Color(red: 0.46, green: 0.07, blue: 0.06)
            VStack(spacing: 10) {
                HStack(spacing: 14) {
                    BundledImage(name: "ransom_idle")
                        .frame(width: 125, height: 125)
                    VStack(alignment: .leading, spacing: 6) {
                        Text("YOUR FILES HAVE\nBEEN ENCRYPTED")
                            .font(.system(size: 28, weight: .black, design: .monospaced))
                            .tracking(-1).lineLimit(2).minimumScaleFactor(0.8)
                        Text("ИГРОВАЯ ИМИТАЦИЯ · ФАЙЛЫ НЕ ШИФРУЮТСЯ")
                            .font(.system(size: 8, weight: .bold, design: .monospaced))
                            .foregroundStyle(.white.opacity(0.75))
                    }
                    Spacer(minLength: 0)
                }
                .frame(height: 130)

                Text("НАЙДИ МОНЕТЫ В FINDER И ОТДАЙ ВЫКУП ДО КОНЦА ТАЙМЕРА")
                    .font(.system(size: 12, weight: .heavy, design: .monospaced))
                    .multilineTextAlignment(.center)
                    .frame(maxWidth: .infinity).padding(.vertical, 11)
                    .background(.black.opacity(0.7))

                HStack(spacing: 11) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("ОСТАЛОСЬ ЗОЛОТА").font(.system(size: 9, weight: .bold, design: .monospaced))
                        Text("\(game.due) G").font(.system(size: 30, weight: .black, design: .monospaced))
                    }
                    .foregroundStyle(Palette.gold)
                    Spacer()
                    VStack(alignment: .trailing, spacing: 2) {
                        Text("TIME").font(.system(size: 9, weight: .bold, design: .monospaced))
                        Text(String(format: "%02d:%02d", game.secondsLeft / 60, game.secondsLeft % 60))
                            .font(.system(size: 30, weight: .black, design: .monospaced))
                    }
                }
                .padding(.horizontal, 11)

                ZStack {
                    RoundedRectangle(cornerRadius: 8)
                        .fill(isDropTarget ? Palette.gold.opacity(0.25) : .black.opacity(0.75))
                    RoundedRectangle(cornerRadius: 8)
                        .strokeBorder(isDropTarget ? Palette.gold : .white.opacity(0.65), style: StrokeStyle(lineWidth: 2, dash: [5, 4]))
                    Text("ПЕРЕТАЩИ СЮДА .gold ИЛИ .crucifix")
                        .font(.system(size: 12, weight: .black, design: .monospaced))
                }
                .frame(height: 70)
                .onDrop(of: [.fileURL], isTargeted: $isDropTarget) { providers in
                    for provider in providers {
                        provider.loadItem(forTypeIdentifier: UTType.fileURL.identifier, options: nil) { item, _ in
                            let fileURL: URL?
                            if let url = item as? URL { fileURL = url }
                            else if let data = item as? Data { fileURL = URL(dataRepresentation: data, relativeTo: nil) }
                            else if let text = item as? String { fileURL = URL(string: text) }
                            else { fileURL = nil }
                            if let fileURL { DispatchQueue.main.async { game.payFile(at: fileURL) } }
                        }
                    }
                    return true
                }

                HStack(spacing: 10) {
                    Button("ОТКРЫТЬ МОНЕТЫ В FINDER") { game.openCoinsInFinder() }
                        .buttonStyle(PrimaryButtonStyle())
                    Button("ВЫБРАТЬ ФАЙЛ…") { game.chooseCoinsToPay() }
                        .buttonStyle(SecondaryButtonStyle())
                }
            }
            .padding(20)
        }
        .foregroundStyle(.white)
        .preferredColorScheme(.dark)
    }
}

private struct PrimaryButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.system(size: 12, weight: .heavy, design: .monospaced))
            .tracking(1.2).foregroundStyle(.white)
            .padding(.vertical, 17)
            .background(configuration.isPressed ? Palette.red.opacity(0.72) : Palette.red, in: RoundedRectangle(cornerRadius: 11))
    }
}

private struct SecondaryButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.system(size: 11, weight: .heavy, design: .monospaced))
            .tracking(0.8).foregroundStyle(Palette.white)
            .frame(maxWidth: .infinity).padding(.vertical, 17)
            .background(configuration.isPressed ? Palette.border : Palette.panelRaised, in: RoundedRectangle(cornerRadius: 11))
            .overlay(RoundedRectangle(cornerRadius: 11).stroke(Palette.border, lineWidth: 1))
    }
}

private struct StepButtonStyle: ButtonStyle {
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.system(size: 12, weight: .bold))
            .frame(width: 29, height: 29)
            .background(configuration.isPressed ? Palette.border : Palette.panelRaised, in: RoundedRectangle(cornerRadius: 7))
            .overlay(RoundedRectangle(cornerRadius: 7).stroke(Palette.border, lineWidth: 1))
    }
}

@main
struct RANS0MMacApp: App {
    @NSApplicationDelegateAdaptor(ExitDelegate.self) private var appDelegate

    var body: some Scene {
        WindowGroup("doors") {
            GameView()
        }
        .windowResizability(.contentMinSize)
    }
}

@MainActor
final class ExitDelegate: NSObject, NSApplicationDelegate {
    func applicationWillTerminate(_ notification: Notification) {
        Game.shared.shutdown()
    }
}
